### ISSUE TITLE
Alphabetize Candidates and Categories dropdown 

### ISSUE THREAD

**Issue by sonjakhan** [aaronnech/CheckYourBias#33]
we pull this from the database, which is not sorted. We should sort for the front end

**Comment by g-liu** [comment]
<del>I would want to have all sorting done in the backend, since it is doing the heavy lifting.</del> Edit: see https://github.com/aaronnech/CheckYourBias/issues/33#issuecomment-189484883

**Comment by sonjakhan** [comment]
@g-liu sure that sounds good. Anyone on backend want to take this?

**Comment by g-liu** [comment]
Reopening, since sorting candidates and categories destroys the invariant that the index of the category/candidate corresponds to their Id.

Will probably end up creating two methods to deal with returning all cat/candidates. One will return with the above invariant, the other will return sorted. Or we can just have 1 method in the backend and deal with sorting in the front end.

**Comment by g-liu** [comment]
Reopening this issue... it's harder than simply calling `get**Sorted()`. Because some of our frontend code depends on having indices corresponding to item ID's, calling `get**Sorted()` will break that assumption.

So we have two options here:
1. Keep the `get**Sorted` methods in the backend, but for each object in the sorted array, include its id as a key-value pair. **Advantages:** Moves all the heavy lifting to the backend. **Disadvantages:** Requires an additional field for each category.
2. Get rid of the `get**Sorted` methods, have sorting be done in the front-end so that the front-end can peek at the ids in the unsorted array, before sorting that array. **Advantages:** Preserves view-model independence. **Disadvantages:** One-time cost penalty for sorting (when `componentWillMount` method is called); could be expensive.

**Comment by SonjaKhan** [comment]
@toddis

**Comment by g-liu** [comment]
@toddis thanks! As discussed today we also want `getAllCategoriesSorted` to implement similar behavior.

**Comment by g-liu** [comment]
@SonjaKhan No worries, I already fixed this (for the 3rd time :laughing:). You can double-check that the menu works properly.
